services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000  # This will be updated when backend is ready
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - packageml-network

networks:
  packageml-network:
    driver: bridge 